åv-te-me	NAIBE	// uvtedh+V+PrfPrc
år-roeh-sij-jien--	NABOIEX,NtPABIX,NePAEBOX	// årroeh#sijjie+N+SgGenCmp+RCmpnd-
år-roeh-sij-jien	NePBO,NePIE,NAB	// årroeh#sijjie+N+SgGenCmp+RCmpnd
år-roeh-sij-jien	NABO	// årroeh#sijjie+N+SgGenCmp+RCmpnd
år-roeh-sij-jien	GaBO	// årroeh#sijjie+N+SgGenCmp+RCmpnd
år-roeh-sij-jiej--	NABOIEX,NtPABIX,NePAEBOX	// årroeh#sijjie+N+PlGenCmp+RCmpnd-
år-roeh-sij-jiej	NAIE,NePAE	// årroeh#sijjie+N+Pl+Gen
år-roeh-sij-jiej	NABO	// årroeh#sijjie+N+PlGenCmp+RCmpnd
år-roeh-sij-jiej	GpBO	// årroeh#sijjie+N+PlGenCmp+RCmpnd
år-roeh-sij-jieh	NAIE,NePAE	// årroeh#sijjie+N+Pl+Nom
år-roeh-sij-jie--	NABOX,NtPABIEX,NePAEBOX	// årroeh#sijjie+N+Sg+Nom-
år-roeh-sij-jie--	NABOIEX,NtPABIX,NePAEBOX	// årroeh#sijjie+N+SgNomCmp+RCmpnd-
år-roeh-sij-jie	NAIE,NePOE	// årroeh#sijjie+N+Sg+Nom
år-roeh-sij-jie	NABO	// årroeh#sijjie+N+SgNomCmp+RCmpnd
år-roeh-sij-ji--	NABOIEX,NtPABIX,NePAEBOX	// årroeh#sijjie+N+PlGenCmp+RCmpnd-
år-roeh-sij-ji	NAIE,NePAE	// årroeh#sijjie+N+Pl+Gen
år-roeh-sij-ji	NABO	// årroeh#sijjie+N+PlGenCmp+RCmpnd
år-roeh-sij-ji	GpBO	// årroeh#sijjie+N+PlGenCmp+RCmpnd
Åarjelsaemien, version 1.2, 20111116--49989	WI
vih-ke-li--	NABOIEX,NtPABIX,NePAEBOX	// vihkeles+A+PlGenCmp+RCmpnd-
vih-ke-li	NABO	// vihkeles+A+PlGenCmp+RCmpnd
vih-ke-li	GpBO,NAIE,NePAE	// vihkeles+A+Pl+Gen
vih-ke-li	GpBO	// vihkeles+A+PlGenCmp+RCmpnd
vih-ke-les--	NABOX,NtPABIEX,NePAEBOX	// vihkeles+A+Sg+Nom-
vih-ke-les	NAIE,NePOE	// vihkeles+A+Sg+Nom
vih-ke-les	NAIBOE	// vihkeles+A+Attr+RCmpnd
vih-ke-les	NAIBOE	// vihkeles+A+Attr
vih-ke-les	NABO	// vihkeles+A+Attr+RCmpnd
vih-ke-len--	NABOIEX,NtPABIX,NePAEBOX	// vihkeles+A+SgGenCmp+RCmpnd-
vih-ke-len	NePBO,NtPABIX,NAB	// vihkeles+A+SgGenCmp+RCmpnd
vih-ke-len	NAIE,NePAE	// vihkeles+A+Sg+Gen
vih-ke-len	NABO	// vihkeles+A+SgGenCmp+RCmpnd
vih-ke-len	GaBO,NAIE	// vihkeles+A+Sg+Gen
vih-ke-len	GaBO	// vihkeles+A+SgGenCmp+RCmpnd
vih-ke-le--	NABOX,NtPABIEX,NePAEBOX	// vihkeles+A+Sg+Nom-
vih-ke-le--	NABOIEX,NtPABIX,NePAEBOX	// vihkeles+A+SgNomCmp+RCmpnd-
vih-ke-le	NAIE,NePOE	// vihkeles+A+Sg+Nom
vih-ke-le	NABO	// vihkeles+A+SgNomCmp+RCmpnd
uv-tien	VI	// uvtedh+V+VGen
uv-tie-mi-nie	VI	// uvtedh+V+Ger
uv-ti-je	VI	// uvtedh+V+PrsPrc
uv-tedh--	NIX,NtPABX	// uvtedh+V+Inf-
uv-tedh	VI	// uvtedh+V+Inf
sij-jien--	NABOIEX,NtPABIX,NePAEBOX	// sijjie+N+SgGenCmp+RCmpnd-
sij-jien	NePBO,NePIE,NAB	// sijjie+N+SgGenCmp+RCmpnd
sij-jien	NAIE,NePAE	// sijjie+N+Sg+Gen
sij-jien	NABO	// sijjie+N+SgGenCmp+RCmpnd
sij-jien	GaBO	// sijjie+N+SgGenCmp+RCmpnd
sij-jiej--	NABOIEX,NtPABIX,NePAEBOX	// sijjie+N+PlGenCmp+RCmpnd-
sij-jiej	NAIE,NePAE	// sijjie+N+Pl+Gen
sij-jiej	NABO	// sijjie+N+PlGenCmp+RCmpnd
sij-jiej	GpBO	// sijjie+N+PlGenCmp+RCmpnd
sij-jieh	NAIE,NePAE	// sijjie+N+Pl+Nom
sij-jie--	NABOX,NtPABIEX,NePAEBOX	// sijjie+N+Sg+Nom-
sij-jie--	NABOIEX,NtPABIX,NePAEBOX	// sijjie+N+SgNomCmp+RCmpnd-
sij-jie	NAIE,NePOE	// sijjie+N+Sg+Nom
sij-jie	NABO	// sijjie+N+SgNomCmp+RCmpnd
sij-ji--	NABOIEX,NtPABIX,NePAEBOX	// sijjie+N+PlGenCmp+RCmpnd-
sij-ji	NAIE,NePAE	// sijjie+N+Pl+Gen
sij-ji	NABO	// sijjie+N+PlGenCmp+RCmpnd
sij-ji	GpBO	// sijjie+N+PlGenCmp+RCmpnd
s:n	NI	// s+N+ABBR+Gen
s.	NI	// s+N+ABBR+Nom
s.	NI	// s+N+ABBR+Attr
s--	NePABX	// s+N+ABBR+RCmpnd-
s	NI	// s+N+ABBR+Attr
ov-ten	VI	// uvtedh+V+Der/PassS+V+VGen
ov-tedh--	NIX,NtPABX	// uvtedh+V+Der/PassS+V+Inf-
ov-tedh	VI	// uvtedh+V+Der/PassS+V+Inf
ov-te-mi-nie	VI	// uvtedh+V+Der/PassS+V+Ger
ov-te-me	VI	// uvtedh+V+Der/PassS+V+PrfPrc
ov-te-me	NAIBE	// uvtedh+V+Der/PassS+V+PrfPrc
eer-pijh	NtPA+,NePIE	// eerpije+N+Pl+Nom
eer-pi-ji--	NePABO	// eerpije+N+PlGenCmp+RCmpnd-
eer-pi-ji--	NAPIX,NAPB,NePABO	// eerpije+N+PlGenCmp+RCmpnd-
eer-pi-ji	NtPA+,NePIE	// eerpije+N+Pl+Gen
eer-pi-ji	GpBO	// eerpije+N+PlGenCmp+RCmpnd
eer-pi-jen--	NAPIX,NAPB,NePABO	// eerpije+N+SgGenCmp+RCmpnd-
eer-pi-jen--	NABOIEX,NtPABX,NePAEOX	// eerpije+N+SgGenCmp+RCmpnd-
eer-pi-jen	NtPA+,NePIE	// eerpije+N+Sg+Gen
eer-pi-jen	NePBO,NePIE,NAB	// eerpije+N+SgGenCmp+RCmpnd
eer-pi-jen	GaBO	// eerpije+N+SgGenCmp+RCmpnd
eer-pi-je--	NAB,NIX,NePOE	// eerpije+N+Sg+Nom-
eer-pi-je	NePOE,NAB	// eerpije+N+SgNomCmp+RCmpnd
eer-pi-je	NePIE	// eerpije+N+Sg+Nom
eekh	NtPA+,NePIE	// eeke+N+Pl+Nom
ee-ki--	NAPIX,NAPB,NePABO	// eeke+N+PlGenCmp+RCmpnd-
ee-ki	GpAB,NePIE	// eeke+N+Pl+Gen
ee-ki	GpAB	// eeke+N+PlGenCmp+RCmpnd
ee-ken--	NAPIX,NAPB,NePABO	// eeke+N+SgGenCmp+RCmpnd-
ee-ken--	NABOIEX,NtPABX,NePAEOX	// eeke+N+SgGenCmp+RCmpnd-
ee-ken	NePABO,NAB,NePIE	// eeke+N+Sg+Gen
ee-ken	GaBO	// eeke+N+SgGenCmp+RCmpnd
ee-keh	NtPA+,NePIE	// eeke+N+Pl+Nom
ee-ke--	NAPIX,NAPB,NePABO	// eeke+N+Sg+Nom-
ee-ke	NePOE,NAB	// eeke+N+SgNomCmp+RCmpnd
ee-ke	NePIE	// eeke+N+Sg+Nom
as:n	NI,NePE	// as+N+ACR+Sg+Gen
as:j	NI,NePE	// as+N+ACR+Pl+Gen
as:h	NI,NePE	// as+N+ACR+Pl+Nom
as--	NePABO,NtPABIX	// as+N+ACR+RCmpnd-
as	NePE	// as+N+ACR+RCmpnd
as	NI,NePE	// as+N+ACR+Sg+Nom
Trond Trosterud	WI
Tomi Pieski	WI
Thomas Omma	WI
Steinar Nilsen	WI
Sjur Moshagen	WI
Saara Huhmarniemi	WI
Risten Turi Aleksandersen	WI
Per--Eric Kuoljok	WI
Os-lon--	NeAIX,NePABO,NePAEX	// Oslo+N+Prop+Plc+Sg+Gen-
Os-lon	NePE	// Oslo+N+Prop+Plc+Sg+Gen
Os-loj--	NeAIX,NePABO,NePAEX	// Oslo+N+Prop+Plc+Pl+Gen-
Os-loj	NAI	// Oslo+N+Prop+Plc+Pl+Gen
Os-loh	NePI	// Oslo+N+Prop+Plc+Pl+Nom
Os-lo--	NAPIBX,NePABO	// Oslo+N+Prop+Plc+Sg+Nom-
Os-lo--	NABIX	// Oslo+N+Prop+Plc+RCmpnd-
Os-lo	NePOE	// Oslo+N+Prop+Plc+Sg+Nom
NRK:n	NI,NePE	// NRK+N+ACR+Sg+Gen
NRK:j	NI,NePE	// NRK+N+ACR+Pl+Gen
NRK:h	NI,NePE	// NRK+N+ACR+Pl+Nom
NRK--	NePABO,NtPABIX	// NRK+N+ACR+RCmpnd-
NRK	NePE	// NRK+N+ACR+RCmpnd
NRK	NI,NePE	// NRK+N+ACR+Sg+Nom
Marit Julien	WI
Maaren Palismaa	WI
Lomh	NePI	// Lom+N+Prop+Sur+Pl+Nom
Lom--	NAPIBX,NePABO	// Lom+N+Prop+Sur+Sg+Nom-
Lom--	NABIX	// Lom+N+Prop+Sur+RCmpnd-
Lom	NePOE	// Lom+N+Prop+Sur+Sg+Nom
Lom	NePI	// Lom+N+Prop+Sur+Attr
Lo-mi--	NeAIX,NePABO,NePAEX	// Lom+N+Prop+Sur+Pl+Gen-
Lo-mi	NAI	// Lom+N+Prop+Sur+Pl+Gen
Lo-men--	NeAIX,NePABO,NePAEX	// Lom+N+Prop+Sur+Sg+Gen-
Lo-men	NePE	// Lom+N+Prop+Sur+Sg+Gen
Lo-meh	NePI	// Lom+N+Prop+Sur+Pl+Nom
Linda Wiechetek	WI
Lene Antonsen	WI
Inga Lill Sigga Mikkelsen	WI
Ilona Kivinen	WI
Har-stadh	NePI	// Harstad+N+Prop+Plc+Pl+Nom
Har-stad--	NAPIBX,NePABO	// Harstad+N+Prop+Plc+Sg+Nom-
Har-stad--	NABIX	// Harstad+N+Prop+Plc+RCmpnd-
Har-stad	NePOE	// Harstad+N+Prop+Plc+Sg+Nom
Har-stad	NePI	// Harstad+N+Prop+Plc+Attr
Har-sta-di--	NeAIX,NePABO,NePAEX	// Harstad+N+Prop+Plc+Pl+Gen-
Har-sta-di	NAI	// Harstad+N+Prop+Plc+Pl+Gen
Har-sta-den--	NeAIX,NePABO,NePAEX	// Harstad+N+Prop+Plc+Sg+Gen-
Har-sta-den	NePE	// Harstad+N+Prop+Plc+Sg+Gen
Har-sta-deh	NePI	// Harstad+N+Prop+Plc+Pl+Nom
Divvun	WI
CD:n	NI,NePE	// CD+N+ACR+Sg+Gen
CD:j	NI,NePE	// CD+N+ACR+Pl+Gen
CD:h	NI,NePE	// CD+N+ACR+Pl+Nom
CD--	NePABO,NtPABIX	// CD+N+ACR+RCmpnd-
CD	NePE	// CD+N+ACR+RCmpnd
CD	NI,NePE	// CD+N+ACR+Sg+Nom
Børre Gaup	WI
A:n	NI	// A+N+ABBR+Gen
A.	NI	// A+N+ABBR+Nom
A.	NI	// A+N+ABBR+Attr
A--	NIOX,NtBOX,NBOX,NePBOX	// A+N+ABBR+RCmpnd-
A	NtEX,WEX,NePEX	// A+N+ABBR+RCmpnd
A	NI	// A+N+ABBR+Nom
A	NI	// A+N+ABBR+Attr
--Os-loh	NePAIBX	// -Oslo+N+Prop+Plc+Pl+Nom
--Os-lo--	NAPOX,NtPAOX,NtAOX,NAOX,NePABIX	// -Oslo+N+Prop+Plc+Sg+Nom-
--Os-lo	NePAIBX	// -Oslo+N+Prop+Plc+Sg+Nom
--Os-lo	NePAIBX	// -Oslo+N+Prop+Plc+Attr
--Lomh	NePAIBX	// -Lom+N+Prop+Sur+Pl+Nom
--Lom--	NAPOX,NtPAOX,NtAOX,NAOX,NePABIX	// -Lom+N+Prop+Sur+Sg+Nom-
--Lom	NePAIBX	// -Lom+N+Prop+Sur+Sg+Nom
--Lom	NePAIBX	// -Lom+N+Prop+Sur+Attr
--Lo-meh	NePAIBX	// -Lom+N+Prop+Sur+Pl+Nom
--Har-stadh	NePAIBX	// -Harstad+N+Prop+Plc+Pl+Nom
--Har-stad--	NAPOX,NtPAOX,NtAOX,NAOX,NePABIX	// -Harstad+N+Prop+Plc+Sg+Nom-
--Har-stad	NePAIBX	// -Harstad+N+Prop+Plc+Sg+Nom
--Har-stad	NePAIBX	// -Harstad+N+Prop+Plc+Attr
--Har-sta-deh	NePAIBX	// -Harstad+N+Prop+Plc+Pl+Nom
