spellername = "South S치mi"
spellerversion = "4.6.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "South S치mi spellchecker"
sma = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for South S치mi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sma = "TRANSLATE: A spellchecker for South S치mi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sma"

[windows]
system_product_code = "{1099F002-6534-45EC-8746-9C8B9A52E42D}_is1"
legacy_product_codes = [
    { value = "4F5DBECF-5760-487C-9CAB-62DAA3A86EAF", kind = "nsis" },
    { value = "51852B34-FDAC-5748-B467-CF731D711EE0", kind = "nsis" }
]
extra_locales = { sma-SE = "sma", sma-NO = "sma" }
