name = "South Sami"
version = "4.2.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sma"

[windows]
system_product_code = "51852B34-FDAC-5748-B467-CF731D711EE0"
msoffice_product_code = "4F5DBECF-5760-487C-9CAB-62DAA3A86EAF"
