template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "sout2674"
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South Sámi"
__UND__ = "sma"
