template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "sout2674"
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South Sámi"
__UND__ = "sma"
